#!/usr/bin/env bash

set -e

export DDE_WORKDIR=$(cd $(dirname $0) && pwd)

export CID_DIR="$DDE_WORKDIR/cids"

# ensure CID_DIR exists
[[ ! -d "$CID_DIR" ]] && mkdir -p $CID_DIR

dde_help() {
  dde_name=${0##*/}
  echo "
$dde_name
Docker Dev Environment CLI
Version: $(cat $DDE_WORKDIR/VERSION)
https://github.com/blitterated/docker_dev_env_cli
Usage: $dde_name [command]
Commands:
  start     Start, and create if necessary, a single instance of any DDE container
  stop      Stop a running DDE container
  exec      Run a command against a running DDE container with docker exec
  attach    Create a new shell process via docker exec
  status    Show the status/existance of a DDE container
  rm        Remove a container and its CID file
  *         Help
"
  exit 1
}

# ensure a command was provided
[[ $# -eq 0 ]] && dde_help

# grab the command and pop it off the arguments
CMD=$1
shift

CMD_DIR="$DDE_WORKDIR/commands"

case "$CMD" in
  start)
    "$CMD_DIR/start" "$@"
    ;;
  stop)
    "$CMD_DIR/stop" "$@"
    ;;
  exec|x)
    "$CMD_DIR/exec" "$@"
    ;;
  attach|a)
    "$CMD_DIR/attach" "$@"
    ;;
  status|s)
    "$CMD_DIR/status" "$@"
    ;;
  rm)
    "$CMD_DIR/rm" "$@"
    ;;
  *|"")
    dde_help
    ;;
esac
