#!/usr/bin/env bash

set -e

source ${DDE_WORKDIR}/share/containers.sh

help_run() {
  echo "
Command: run
Usage:
  run image_name"
  exit 1
}

[ ! -n "$1" ] && help_run

IMAGE_NAME=$1
shift

CID_FILE="${CID_DIR}/${IMAGE_NAME}"

ensure_container_exists

read CID < "$CID_FILE"

ensure_container_not_running

rm $CID_FILE
docker rm "$CID"
