#!/usr/bin/env bash

set -e

source ${DDE_WORKDIR}/share/containers.sh

help_stop() {
  echo "
Command: stop
Usage:
  stop image_name"
  exit 1
}

[ ! -n "$1" ] && help_stop

IMAGE_NAME=$1
shift

CID_FILE="${CID_DIR}/${IMAGE_NAME}"

ensure_container_exists

read CID < "$CID_FILE"

ensure_container_running

docker stop "$CID"
# docker stop will output the container's full id
